# EOD Historical Data API configuration
api_key: "your_real_key_here"

# Supported European Equity Symbols
symbols:
  ASML: "ASML.AS"
  PHIA: "PHIA.AS"
  INGA: "INGA.AS"
  AD: "AD.AS"
  OR: "OR.PA"
  SAN: "SAN.PA"