# EOD Historical Data API configuration
api_key: !!ENV ${EOD_API_KEY}

# Supported European Equity Symbols
symbols:
  ASML: "ASML.AS"
  PHIA: "PHIA.AS"
  INGA: "INGA.AS"
  AD: "AD.AS"
  OR: "OR.PA"
  SAN: "SAN.PA"