name: CI/CD Pipeline

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Run pip-audit for security
      - name: Run pip-audit
        run: pip install pip-audit && pip-audit

      - name: Install Python linters
        run: pip install flake8 black isort

      - name: Auto-fix Python code style with black and isort
        run: |
          black .
          isort .
          flake8 app/ strategies/ tests/ api/

      # Set up Node.js for JS linting
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint
        run: npm install eslint --global

      - name: Lint and auto-fix app.js
        run: eslint --fix api/static/app.js

      # Run tests with coverage and upload to Codecov
      - name: Run tests with coverage
        run: pytest --cov=app --cov=strategies --cov-report=xml tests/

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: [lint-test, security-scan]
    steps:
      - uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Deploy to Azure Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: OrderBookHFT-Pilot
          slot-name: staging                     # Optional for slots
          publish-profile: ${{ secrets.AZURE_STAGING_PUBLISH_PROFILE }}
          package: .

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [lint-test, security-scan]
    steps:
      - uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Deploy to Azure Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: OrderBookHFT
          publish-profile: ${{ secrets.AZURE_PRODUCTION_PUBLISH_PROFILE }}
          package: .
