name: CI/CD Pipeline

on:
  pull_request:
    branches: [pilot, staging, main]
  push:
    branches: [pilot, staging, main]

permissions:
  actions: read
  contents: read
  security-events: write
  packages: write

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Python dependencies and dev tools
        run: |
          pip install -r requirements.txt
          pip install flake8 black isort mypy pip-audit bandit pytest pytest-cov types-requests pandas-stubs types-PyYAML
      - name: Run pip-audit
        run: pip-audit
      - name: Auto-fix Python code style with black and isort
        run: |
          black .
          isort .
      - name: Run flake8
        run: flake8 app/ strategies/ tests/ api/
      - name: Run mypy (ignore missing imports)
        run: mypy --ignore-missing-imports app/ strategies/ tests/ api/
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install ESLint
        run: npm install eslint --global
      - name: Lint and auto-fix app.js
        run: eslint --fix api/static/app.js

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit security scanner
        run: bandit -r app/ strategies/ api/ || true
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  unit-tests:
    runs-on: ubuntu-latest
    needs: [lint-test, security-scan]
    steps:
      - uses: actions/checkout@v4
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies and dev tools
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run unit tests with coverage
        run: pytest --cov=app --cov=strategies --cov-report=xml --cov-report=term-missing tests/Unit/

  integration-tests:
    runs-on: ubuntu-latest
    needs: [ lint-test, security-scan ]
    env:
      EOD_API_KEY: ${{ secrets.EOD_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies and dev tools
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: (Optional) Debug - Show if API key present
        run: |
          if [ -z "$EOD_API_KEY" ]; then
            echo "EOD_API_KEY is not set!"
            exit 1
          else
            echo "EOD_API_KEY is set (length: ${#EOD_API_KEY})"
          fi
      - name: Start application server
        run: |
          python3 -m api.server &
          for i in {1..10}; do
            nc -z 127.0.0.1 8000 && echo "Server up!" && exit 0
            sleep 2
          done
          echo "Server did not start in time" && exit 1
      - name: Run integration tests with coverage
        run: pytest --cov=app --cov=strategies --cov-report=xml --cov-append tests/Integration/
        env:
          PYTHONUNBUFFERED: 1

  system-tests:
    runs-on: ubuntu-latest
    needs: [lint-test, security-scan]
    steps:
      - uses: actions/checkout@v4
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies and dev tools
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Start application server
        run: |
          python3 -m api.server &
          for i in {1..10}; do
            nc -z 127.0.0.1 8000 && echo "Server up!" && exit 0
            sleep 2
          done
          echo "Server did not start in time" && exit 1
      - name: Run system tests with coverage
        run: pytest --cov=app --cov=strategies --cov-report=xml --cov-append tests/System/
        env:
          PYTHONUNBUFFERED: 1

  docker-build:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, system-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/orderbookhft:${{ github.sha }} .
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/orderbookhft:${{ github.sha }}

  deploy-pilot:
    if: github.ref == 'refs/heads/pilot'
    runs-on: ubuntu-latest
    needs: [docker-build]
    environment: pilot
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Azure Pilot
        uses: azure/webapps-deploy@v2
        with:
          app-name: OrderBookHFT-Pilot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PILOT }}
          images: ghcr.io/${{ github.repository_owner }}/orderbookhft:${{ github.sha }}

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    needs: [docker-build]
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Azure Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: OrderBookHFT-Staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          images: ghcr.io/${{ github.repository_owner }}/orderbookhft:${{ github.sha }}

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [docker-build]
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Azure Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: OrderBookHFT-Prod
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          images: ghcr.io/${{ github.repository_owner }}/orderbookhft:${{ github.sha }}