name: CI/CD Pipeline

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Python linters
        run: pip install flake8 black isort

      - name: Run Python linters
        run: |
          flake8 app/ strategies/ tests/ api/
          black --check .
          isort --check-only .

      - name: Run Python tests
        run: pytest tests/

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: [lint-test, security-scan]
    steps:
      - uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Deploy to Azure Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: OrderBookHFT-Pilot
          slot-name: staging                     # Optional for slots
          publish-profile: ${{ secrets.AZURE_STAGING_PUBLISH_PROFILE }}
          package: .

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [lint-test, security-scan]
    steps:
      - uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Deploy to Azure Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: OrderBookHFT
          publish-profile: ${{ secrets.AZURE_PRODUCTION_PUBLISH_PROFILE }}
          package: .
